# Generated by Django 3.2.9 on 2022-01-12 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0006_rename_location_event_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='gamer',
            new_name='organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
    ]
