# Generated by Django 3.2.9 on 2022-01-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0007_auto_20220112_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(null=True, related_name='attending', to='levelupapi.Gamer'),
        ),
    ]
